// Generated by Creer at 03:39AM on October 10, 2015 UTC, git hash: '98604e3773d1933864742cb78acbf6ea0b4ecd7b'
// This is where you build your AI for the Anarchy game.

var Class = require(__basedir + "/joueur/class");
var BaseAI = require(__basedir + "/joueur/baseAI");

// <<-- Creer-Merge: requires -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
// any additional requires you want can be required here safely between creer runs
// <<-- /Creer-Merge: requires -->>

/**
 * This is the class to play the Anarchy game. This is where you should build your AI.
 * @class
 */
var AI = Class(BaseAI, {
    /**
     * this is the name you send to the server to play as.
     */
    getName: function() {
        // <<-- Creer-Merge: getName -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
        return "Anarchy JavaScript Player";
        // <<-- /Creer-Merge: getName -->>
    },

    /**
     * this is called once the game starts and your AI knows its playerID and game. You can initialize your AI here.
     */
    start: function() {
        // <<-- Creer-Merge: start -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
        // pass
        // <<-- /Creer-Merge: start -->>
    },

    /**
     * this is called every time the game's state updates, so if you are tracking anything you can update it here.
     */
    gameUpdated: function() {
        // <<-- Creer-Merge: gameUpdated -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
        // pass
        // <<-- /Creer-Merge: gameUpdated -->>
    },

    /**
     * this is called when the game ends, you can clean up your data and dump files here if need be
     *
     * @param {boolean} won - true means you won, false means you lost
     * @param {string} reason - the human readable string explaining why you won or lost
     */
    ended: function(won, reason) {
        // <<-- Creer-Merge: ended -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
        // pass
        // <<-- /Creer-Merge: ended -->>
    },



    /**
     * This is called every time the AI is asked to respond with a command during their turn
     *
     * @returns {boolean} represents if you want to end your turn. true means end the turn, false means to keep your turn going and re-call runTurn()
     */
    runTurn: function() {
        // <<-- Creer-Merge: runTurn -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
        // Put your game logic here for runTurn
        return true;
        // <<-- /Creer-Merge: runTurn -->>
    },


    //<<-- Creer-Merge: functions -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
    // any additional functions you want to add for your AI
    //<<-- /Creer-Merge: functions -->>

});

module.exports = AI;
