// Generated by Creer at 08:11PM on February 04, 2016 UTC, git hash: '955970b8006ac45cc438822363db1bc1242d9868'
// This is a simple class to represent the Warehouse object in the game. You can extend it by adding utility functions here in this file.

var Class = require("classe");
var client = require(__basedir + "/joueur/client");
var Building = require("./building");


//<<-- Creer-Merge: requires -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
// any additional requires you want can be required here safely between creer runs
//<<-- /Creer-Merge: requires -->>

/**
 * @class
 * @classdesc A typical abandoned warehouse... that anarchists hang out in and can be bribed to burn down Buildings.
 * @extends Building
 */
var Warehouse = Class(Building, {
    /**
     * initializes a Warehouse with basic logic as provided by the Creer code generator
     *
     * @memberof Warehouse
     * @private
     */
    init: function() {
        Building.init.apply(this, arguments);


        // The following values should get overridden when delta states are merged, but we set them here as a reference for you to see what variables this class has.


        /**
         * How exposed the anarchists in this warehouse are to PoliceDepartments. Raises when bribed to ignite buildings, and drops each turn if not bribed.
         *
         * @name Warehouse#exposure
         * @type number
         */
        this.exposure = 0;

        /**
         * The amount of fire added to buildings when bribed to ignite a building. Headquarters add more fire than normal Warehouses.
         *
         * @name Warehouse#fireAdded
         * @type number
         */
        this.fireAdded = 0;

        //<<-- Creer-Merge: init -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
        // any additional init logic you want can go here
        //<<-- /Creer-Merge: init -->>

    },


    /**
     * Bribes the Warehouse to light a Building on fire. This adds this building's fireAdded to their fire, and then this building's exposure is increased based on the Manhatten distance between the two buildings.
     *
     * @memberof Warehouse
     * @instance
     * @param {Building} building - The Building you want to light on fire.
     * @returns {number} - The exposure added to this Building's exposure. -1 is returned if there was an error.
     */
    ignite: function(building) {
        return client.runOnServer(this, "ignite", {
            building: building,
        });
    },


    //<<-- Creer-Merge: functions -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
    // any additional functions you want to add to this class can be perserved here
    //<<-- /Creer-Merge: functions -->>

});

module.exports = Warehouse;
