// Generated by Creer at 03:55PM on April 26, 2015 UTC, git hash: '2acbba9c4b682c4de68840c1ca9bec631e9c635f'
// This is a simple class to represent the Checker object in the game. You can extend it by adding utility functions here in this file.

var Class = require("../utilities/class");
var makeCommand = require("../utilities/command");
var GameObject = require("./gameObject");

/// @class Checker: A checker on the game board.
var Checker = Class(GameObject, {
	/// initializes a Checker with basic logic as provided by the Creer code generator
	init: function() {
		GameObject.init.apply(this, arguments);


		// The following values should get overridden when delta states are merged, but we set them here as a reference for you to see what variables this class has.

		// The x coordinate of the checker.
		this.x = 0;
		// The y coordinate of the checker.
		this.y = 0;
		// The player that controls this Checker.
		this.owner = null;
		// If the checker has been kinged and can move backwards.
		this.kinged = false;
	},


	/// Moves the checker from its current location to the given (x, y).
	// @param <int> x: The x coordinate to move to.
	// @param <int> y: The y coordinate to move to.
	// @return <Command> the command for the server to run this function against game logic, then send back the updated game state
	move: function(x, y) {
		return makeCommand(this, "move", {
			x: x,
			y: y,
		});
	},
});

module.exports = Checker;
