// Generated by Creer, git hash c6767247662bdc8024518de1aebc87bcf634ca49
// This is a simple class to represent the Game object in the game. You can extend it by adding utility functions here in this file.

var Class = require("../utilities/class");
var BaseGame = require("../baseGame");

// game object classes
var Player = require("./player");
var Checker = require("./checker");
var GameObject = require("./gameObject");

/// @class Game: The simple version of American Checkers. An 8x8 board with 12 checkers on each side that much move diagonally to the opposing side. Very simple.
var Game = Class(BaseGame, {
	/// initializes a Game with basic logic as provided by the Creer code generator
	// @param <object> data: initialization data
	init: function(data) {
		BaseGame.init.call(this, data);

		this.checkerMovedJumped = (data.checkerMovedJumped === undefined ? false : data.checkerMovedJumped);
		this.boardHeight = parseInt(data.boardHeight === undefined ? 8 : data.boardHeight);
		this.currentTurn = parseInt(data.currentTurn === undefined ? 0 : data.currentTurn);
		this.maxTurns = parseInt(data.maxTurns === undefined ? 100 : data.maxTurns);
		this.currentPlayer = (data.currentPlayer === undefined ? null : data.currentPlayer);
		this.currentPlayers = (data.currentPlayers === undefined ? [] : data.currentPlayers);
		this.players = (data.players === undefined ? [] : data.players);
		this.checkerMoved = (data.checkerMoved === undefined ? null : data.checkerMoved);
		this.gameObjects = (data.gameObjects === undefined ? {} : data.gameObjects);
		this.checkers = (data.checkers === undefined ? [] : data.checkers);
		this.boardWidth = parseInt(data.boardWidth === undefined ? 8 : data.boardWidth);

		this.name = "Checkers"

		this._gameObjectClasses = {
			"Player": Player,
			"Checker": Checker,
			"GameObject": GameObject,
		};
	},

});

module.exports = Game;
