// Generated by Creer, git hash fa0ddf38a9de12f1ec780817a1333033da78ca83
// This is a simple class to represent the Game object in the game. You can extend it by adding utility functions here in this file.

var Class = require("../utilities/class");
var Command = require("../utilities/command");
var BaseGame = require("../baseGame");

// game object classes
var GameObject = require("./gameObject");
var Checker = require("./checker");
var Player = require("./player");

/// @class Game: The simple version of American Checkers. An 8x8 board with 12 checkers on each side that much move diagonally to the opposing side. Very simple.
var Game = Class(BaseGame, {
	/// initializes a Game with basic logic as provided by the Creer code generator
	// @param <object> data: initialization data
	init: function() {
		BaseGame.init.apply(this, arguments);


		// The following values should get overridden when delta states are merged, but we set them here as a reference for you to see what variables this class has.

		// The width of the board for X component of a checker.
		this.boardWidth = 8;
		// A mapping of every game object's ID to the actual game object. Primarily used by the server and client to easily refer to the game objects via ID.
		this.gameObjects = {};
		// The current turn number, starting at 0 for the first player's turn
		this.currentTurn = 0;
		// The maximum number of turns before the game will automatically end.
		this.maxTurns = 100;
		// The checker that last moved and must be moved because only one checker can move during each players turn.
		this.checkerMoved = null;
		// The player whose turn it is currently. That player can send commands. Other players cannot.
		this.currentPlayer = null;
		// List of all the players in the game.
		this.players = [];
		// All the checkers currently in the game.
		this.checkers = [];
		// The height of the board for the Y component of a checker.
		this.boardHeight = 8;
		// If the last checker that moved jumped, meaning it can move again.
		this.checkerMovedJumped = false;

		this.name = "Checkers"

		this._gameObjectClasses = {
			"GameObject": GameObject,
			"Checker": Checker,
			"Player": Player,
		};
	},

});

module.exports = Game;
