// Generated by Creer, git hash 85ea1f696c6b9066cad480281f599d9c78f16d32
// This is a simple class to represent the GameObject object in the game. You can extend it by adding utility functions here in this file.

var Class = require("../utilities/class");
var BaseGameObject = require("../baseGameObject");

/// @class GameObject: An object in the game. The most basic class that all game classes should inherit from automatically.
var GameObject = Class(BaseGameObject, {
	/// initializes a GameObject with basic logic as provided by the Creer code generator
	// @param <object> data: initialization data
	init: function(data) {
		BaseGameObject.init.call(this, data);

		this.id = parseInt(data.id === undefined ? 0 : data.id);
		this.logs = (data.logs === undefined ? [] : data.logs);
	},


	/// adds a message to this game object's log. Intended for debugging purposes.
	// @param <string> message: A string to add to this GameObject's log. Intended for debugging.
	log: function(message) {
		return this._client.sendCommand(this, "log", {
			message: message,
		});
	},
});

module.exports = GameObject;
