// Generated by Creer, git hash c6767247662bdc8024518de1aebc87bcf634ca49
// This is a simple class to represent the Player object in the game. You can extend it by adding utility functions here in this file.

var Class = require("../utilities/class");
var GameObject = require("./gameObject");

/// @class Player: A player in this game. Every AI controls one player.
var Player = Class(GameObject, {
	/// initializes a Player with basic logic as provided by the Creer code generator
	// @param <object> data: initialization data
	init: function(data) {
		GameObject.init.call(this, data);

		this.clientType = String(data.clientType === undefined ? "" : data.clientType);
		this.timeRemaining = parseInt(data.timeRemaining === undefined ? 0 : data.timeRemaining);
		this.checkers = (data.checkers === undefined ? [] : data.checkers);
		this.yDirection = parseInt(data.yDirection === undefined ? 0 : data.yDirection);
		this.name = String(data.name === undefined ? "Anonymous" : data.name);
		this.loseReason = String(data.loseReason === undefined ? "" : data.loseReason);
		this.lost = (data.lost === undefined ? false : data.lost);
		this.winReason = String(data.winReason === undefined ? "" : data.winReason);
		this.won = (data.won === undefined ? false : data.won);
	},


	/// Tells the server that this player is done with their turn.
	endTurn: function() {
		return this._client.sendCommand(this, "endTurn", {
		});
	},
});

module.exports = Player;
