// Generated by Creer, git hash fa0ddf38a9de12f1ec780817a1333033da78ca83
// This is a simple class to represent the Player object in the game. You can extend it by adding utility functions here in this file.

var Class = require("../utilities/class");
var Command = require("../utilities/command");
var GameObject = require("./gameObject");

/// @class Player: A player in this game. Every AI controls one player.
var Player = Class(GameObject, {
	/// initializes a Player with basic logic as provided by the Creer code generator
	// @param <object> data: initialization data
	init: function() {
		GameObject.init.apply(this, arguments);


		// The following values should get overridden when delta states are merged, but we set them here as a reference for you to see what variables this class has.

		// if the player lost the game or not
		this.lost = false;
		// the reason why the player won the game
		this.winReason = "";
		// The name of the player
		this.name = "Anonymous";
		// All the checkers currently in the game owned by this player
		this.checkers = [];
		// The direction your checkers must go along the y-axis until kinged
		this.yDirection = 0;
		// the reason why the player lost the game
		this.loseReason = "";
		// What type of client this is, e.g. 'Python', 'JavaScript', or some other language. For potential data mining purposes.
		this.clientType = "";
		// The amount of time (in ms) remaining for this AI to send commands.
		this.timeRemaining = 0;
		// if the player won the game or not
		this.won = false;
	},


	/// Tells the server that this player is done with their turn.
	// @return <Command> the command for the server to run this function against game logic, then send back the updated game state
	endTurn: function() {
		return new Command(this, "endTurn", {
		});
	},
});

module.exports = Player;
