// Generated by Creer, git hash 3387ee0c43f2ea6a7c76949338d58308dace22b8
// This is a simple class to represent the Player object in the game. You can extend it by adding utility functions here in this file.

var Class = require("../utilities/class");
var GameObject = require("./gameObject");

/// @class Player: A player in this game. Every AI controls one player.
var Player = Class(GameObject, {
	/// initializes a Player with basic logic as provided by the Creer code generator
	// @param <object> data: initialization data
	init: function(data) {
		GameObject.init.call(this, data);

		this.clientType = String(data.clientType === undefined ? "" : data.clientType);
		this.name = String(data.name === undefined ? "Anonymous" : data.name);
	},


	/// Tells the server that this player is done with their turn.
	endTurn: function() {
		return this._client.sendCommand(this, "endTurn", {
		});
	},
});

module.exports = Player;
