// Generated by Creer at 03:31AM on April 24, 2016 UTC, git hash: '087b1901032ab5bed5806b24830233eac5c2de55'
// This is a simple class to represent the Nest object in the game. You can extend it by adding utility functions here in this file.

var Class = require(__basedir + "/joueur/class");
var client = require(__basedir + "/joueur/client");
var GameObject = require("./gameObject");


//<<-- Creer-Merge: requires -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
// any additional requires you want can be required here safely between creer runs
//<<-- /Creer-Merge: requires -->>

/**
 * @class
 * @classdesc A location (node) connected to other Nests via Webs (edges) in the game that Spiders can converge on, regardless of owner.
 * @extends GameObject
 */
var Nest = Class(GameObject, {
    /**
     * initializes a Nest with basic logic as provided by the Creer code generator
     *
     * @memberof Nest
     * @private
     */
    init: function() {
        GameObject.init.apply(this, arguments);


        // The following values should get overridden when delta states are merged, but we set them here as a reference for you to see what variables this class has.


        /**
         * All the Spiders currently located on this Nest.
         *
         * @name Nest#spiders
         * @type Array.<Spider>
         */
        this.spiders = [];

        /**
         * Webs that connect to this Nest.
         *
         * @name Nest#webs
         * @type Array.<Web>
         */
        this.webs = [];

        /**
         * The X coordinate of the Nest. Used for distance calculations.
         *
         * @name Nest#x
         * @type number
         */
        this.x = 0;

        /**
         * The Y coordinate of the Nest. Used for distance calculations.
         *
         * @name Nest#y
         * @type number
         */
        this.y = 0;

        //<<-- Creer-Merge: init -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
        // any additional init logic you want can go here
        //<<-- /Creer-Merge: init -->>

    },



    //<<-- Creer-Merge: functions -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.

    /**
     * Calculates the distance from this Nest to another Nest
     *
     * @memberof Nest
     * @instance
     * @param {Nest} nest - The nest to calculate the distance to
     * @returns {number} - The euclidean distance between the two Nests
     */
    distanceTo: function(nest) {
        return Math.sqrt( Math.pow(nest.x - this.x, 2) + Math.pow(nest.y - this.y, 2) );
    },

    //<<-- /Creer-Merge: functions -->>

});

module.exports = Nest;
