// Generated by Creer at 04:24PM on March 02, 2016 UTC, git hash: '0cc14891fb0c7c6bec65a23a8e2497e80f8827c1'
// This is a simple class to represent the Web object in the game. You can extend it by adding utility functions here in this file.

var Class = require(__basedir + "/joueur/class");
var client = require(__basedir + "/joueur/client");
var GameObject = require("./gameObject");


//<<-- Creer-Merge: requires -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
// any additional requires you want can be required here safely between creer runs
//<<-- /Creer-Merge: requires -->>

/**
 * @class
 * @classdesc A connection (edge) to a Nest (node) in the game that Spiders can converge on (regardless of owner). Spiders can travel in either direction on Webs.
 * @extends GameObject
 */
var Web = Class(GameObject, {
    /**
     * initializes a Web with basic logic as provided by the Creer code generator
     *
     * @memberof Web
     * @private
     */
    init: function() {
        GameObject.init.apply(this, arguments);


        // The following values should get overridden when delta states are merged, but we set them here as a reference for you to see what variables this class has.


        /**
         * How long this Web is, i.e., the distance between its nestA and nestB.
         *
         * @name Web#length
         * @type number
         */
        this.length = 0;

        /**
         * The first Nest this Web is connected to.
         *
         * @name Web#nestA
         * @type Nest
         */
        this.nestA = null;

        /**
         * The second Nest this Web is connected to.
         *
         * @name Web#nestB
         * @type Nest
         */
        this.nestB = null;

        /**
         * All the Spiderlings currently moving along this Web.
         *
         * @name Web#spiderlings
         * @type Array.<Spiderling>
         */
        this.spiderlings = [];

        /**
         * How much weight this Web can take before snapping and destroying itself and all the Spiders on it.
         *
         * @name Web#strength
         * @type number
         */
        this.strength = 0;

        //<<-- Creer-Merge: init -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
        // any additional init logic you want can go here
        //<<-- /Creer-Merge: init -->>

    },



    //<<-- Creer-Merge: functions -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
    // any additional functions you want to add to this class can be perserved here
    //<<-- /Creer-Merge: functions -->>

});

module.exports = Web;
